"""Recover two existing W03 generations. Reuse intake primitives; never edit pixels."""
from __future__ import annotations
import importlib.util
import io
import json
import os
from pathlib import Path
from PIL import Image
ROOT = Path.cwd().resolve()
spec = importlib.util.spec_from_file_location('existing_intake', ROOT / 'scripts/importShoesRecovery5to6_20260921.py')
helper = importlib.util.module_from_spec(spec)
spec.loader.exec_module(helper)
helper.ROOT = ROOT
REPORT = ROOT / 'docs/preproduction/catalog-sprint/chat-desks-5-6-recovery-result.json'
ORIGINALS = ROOT / 'docs/preproduction/catalog-sprint/recovered-originals/desks-5-6-20260921'
ITEMS = [
 {'id':'desks-5','name':'Garden Book Desk','tier':2,'theme':'Pixel Party','price':181,'starReq':0,
  'assetId':'urn:aaid:sc:US:8962802a-f953-4cfe-bc19-c56fc7afcc74',
  'renditionUrl':'https://at.adobe.com/aLtDG7rKBBKnpbeO','sourceUrl':'https://at.adobe.com/gwm7mXMwCnJlQEEK'},
 {'id':'desks-6','name':'Galaxy Gamer Setup','tier':2,'theme':'Berry Blast','price':254,'starReq':0,
  'assetId':'urn:aaid:sc:US:bc5a80a0-b94a-4564-8360-9d521a05dde0',
  'renditionUrl':'https://at.adobe.com/O5liWph5i09bltxe','sourceUrl':'https://at.adobe.com/JbshHajEPLup9vdy'}
]
EXPECTED = [x['id'] for x in ITEMS]
KEYS = ['id','name','collectionId','collectionName','type','tier','theme','price','starReq']

def inspect(data):
    info = helper.info(data)
    with Image.open(io.BytesIO(data)) as im:
        im.load()
        if 'A' in im.getbands() and im.getchannel('A').getextrema()[1] <= 8:
            raise ValueError('Fully transparent image')
        if all(hi-lo < 4 for lo,hi in im.convert('RGB').getextrema()):
            raise ValueError('Constant/blank image')
    return info

def verify(report, metadata):
    if [x['id'] for x in report['items']] != EXPECTED:
        raise ValueError('Unexpected report IDs')
    seen = set()
    for row in report['items']:
        for key in KEYS:
            if row[key] != metadata[row['id']][key]:
                raise ValueError(f"{row['id']}: metadata drift {key}")
        if row['repositoryPath'] != f"public/assets/catalog/{row['id']}-w03-recovered-v2.jpg":
            raise ValueError('Unexpected destination')
        for record in (row, row['original']):
            file = (ROOT / record['repositoryPath']).resolve()
            if ROOT not in file.parents or file.is_symlink():
                raise ValueError('Unsafe stored path')
            measured = inspect(file.read_bytes())
            for key in ['sha256','gitBlobSha','bytes','dimensions','format']:
                if measured[key] != record[key]:
                    raise ValueError('Stored bytes/measurements changed: '+record['repositoryPath'])
        seen.add(row['sha256'])
    if len(seen) != len(EXPECTED):
        raise ValueError('Duplicate candidate content')

def main():
    helper.guard()
    metadata = helper.store()
    for item in ITEMS:
        real = metadata[item['id']]
        if real['collectionId'] != 'desks' or real['type'] != 'room':
            raise ValueError('Wrong item family')
        for key in ['name','tier','theme','price','starReq']:
            if real[key] != item[key]:
                raise ValueError(f"{item['id']}: request metadata mismatch {key}")
    if REPORT.exists():
        verify(json.loads(REPORT.read_text()), metadata)
        print('2/2 stored Desk candidate/source pairs verified; no download, edits or regeneration')
        return
    prepared = []
    for item in ITEMS:
        candidate = helper.fetch(item['renditionUrl'])
        original = helper.fetch(item['sourceUrl'])
        ci, oi = inspect(candidate), inspect(original)
        if ci['format'] != 'JPEG' or ci['dimensions'] != [600,600]:
            raise ValueError('Unexpected candidate format/dimensions')
        if oi['format'] != 'PNG' or oi['dimensions'] != [1024,1024]:
            raise ValueError('Expected original 1024-square PNG, not a generation container')
        cp = ROOT / f"public/assets/catalog/{item['id']}-w03-recovered-v2.jpg"
        op = ORIGINALS / f"{item['id']}-{item['assetId'].rsplit(':',1)[-1]}.png"
        for file, data in [(cp,candidate),(op,original)]:
            if file.exists() and file.read_bytes() != data:
                raise ValueError('Destination conflict; preserve current bytes: '+str(file))
        for file in (ROOT/'public/assets').rglob('*'):
            if file.is_file() and file.suffix.lower() in {'.jpg','.jpeg','.png','.webp'} and file != cp:
                if file.read_bytes() == candidate and not file.name.startswith(item['id']+'-'):
                    raise ValueError('Identical candidate already assigned elsewhere: '+str(file))
        prepared.append((item,candidate,original,ci,oi,cp,op))
    if len({x[3]['sha256'] for x in prepared}) != len(EXPECTED):
        raise ValueError('Duplicate generated bytes')
    rows=[]
    for item,candidate,original,ci,oi,cp,op in prepared:
        helper.write(cp,candidate); helper.write(op,original)
        row={key:metadata[item['id']][key] for key in KEYS}
        row.update(ci)
        row.update({'assetId':item['assetId'],'producer':'03','transportHelper':'CHAT','independentReviewer':'05',
            'repositoryPath':str(cp.relative_to(ROOT)),'assetPath':'/'+str(cp.relative_to(ROOT/'public')),
            'status':'READY_FOR_REVIEW','readback':'PASS',
            'transformation':'None: exact existing Adobe rendition/source bytes; no resize, crop, recompression or regeneration',
            'original':{**oi,'repositoryPath':str(op.relative_to(ROOT))}})
        rows.append(row)
    report={'schemaVersion':1,'batchId':'chat-desks-5-6-recovery-20260921','sourceHead':helper.head(),
        'workflowRunId':os.environ.get('GITHUB_RUN_ID'),'status':'STAGED_READY_FOR_INDEPENDENT_REVIEW',
        'producer':'03','transportHelper':'CHAT','independentReviewer':'05','canonicalWriter':'08',
        'newGenerations':0,'storedCandidateCount':2,'storedOriginalCount':2,'independentAcceptsThisIntake':0,
        'canonicalPromotionsThisIntake':0,'duplicateCandidateContent':0,'items':rows,
        'checks':{'metadata':'PASS_2_OF_2','sourceCandidateReadback':'PASS_4_OF_4','imageDecodeAndNonblank':'PASS_4_OF_4',
            'tests':'NOT_RUN','build':'NOT_RUN','render':'NOT_RUN','independentVisualReview':'PENDING_05'},
        'reviewNotes':{'desks-5':'Check Pixel Party theme specificity: rich wood/garden/book form is visible but pixel-language may be understated.',
            'desks-6':'Check dark leg/pedestal readability and seemingly floating headphone-like accessories. Not self-approved.'},
        'freeze':{'replitTouched':False,'flootTouched':False,'mainTouched':False,'canonicalMappingsTouched':False,'gameplayChanged':False}}
    REPORT.parent.mkdir(parents=True,exist_ok=True)
    REPORT.write_text(json.dumps(report,indent=2)+'\n')
    verify(report,metadata)
    print(json.dumps({'storedIds':EXPECTED,'hashes':{r['id']:r['gitBlobSha'] for r in rows}},indent=2))

if __name__ == '__main__':
    main()
