import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { chromium } from 'playwright';
import { gameModel } from '../src/gameModel.js';

const BASE_URL=process.env.STARBLOX_QA_URL||'http://127.0.0.1:4173';
const OUTPUT=process.env.STARBLOX_QA_OUTPUT||'artifacts/persistence-recovery-quest-qa';
const SAVE_KEY='starblox-save-v2';
const DB_NAME='starblox';
const STORE_NAME='state';
const questionByPrompt=new Map(gameModel.buildQuestions().map(q=>[q.prompt,q]));
const results=[];
await fs.mkdir(OUTPUT,{recursive:true});

function assert(ok,message,details={}){ if(!ok){ const e=new Error(message); e.details=details; throw e; } }
function critical(s){ return {coins:s?.coins,stars:s?.stars,xp:s?.xp,starWorth:s?.starWorth,owned:[...(s?.owned||[])],purchaseReceipts:[...(s?.purchaseReceipts||[])],equipped:{...(s?.equipped||{})},roomDecor:[...(s?.roomDecor||[])],dreamGoalId:s?.dreamGoalId,questsCompleted:s?.questsCompleted,daily:{...(s?.daily||{})},mastered:[...(s?.mastered||[])],transferWins:s?.transferWins,companionBond:s?.companionBond,districtProgress:{...(s?.districtProgress||{})},activeQuestReceipt:s?.activeQuestReceipt,lastCompletedQuestReceipt:s?.lastCompletedQuestReceipt}; }
async function readSave(page){ return page.evaluate(key=>JSON.parse(localStorage.getItem(key)||'null'),SAVE_KEY); }
async function readIdb(page){ return page.evaluate(async ({dbName,storeName})=>await new Promise(resolve=>{ const request=indexedDB.open(dbName,1); request.onerror=()=>resolve(null); request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(storeName))request.result.createObjectStore(storeName);}; request.onsuccess=()=>{const db=request.result;const tx=db.transaction(storeName,'readonly');const get=tx.objectStore(storeName).get('current');get.onsuccess=()=>{resolve(get.result??null);db.close();};get.onerror=()=>{resolve(null);db.close();};};}),{dbName:DB_NAME,storeName:STORE_NAME}); }
async function waitIdb(page,predicate,timeout=5000){ const start=Date.now(); while(Date.now()-start<timeout){ const value=await readIdb(page); if(value&&predicate(value))return value; await page.waitForTimeout(100); } throw new Error('Timed out waiting for IndexedDB backup'); }
async function waitSave(page,predicate,args=[],timeout=5000){ await page.waitForFunction(({key,args,src})=>{const raw=localStorage.getItem(key);if(!raw)return false;return Function('value','args',`return (${src})(value,args)`)(JSON.parse(raw),args);},{key:SAVE_KEY,args,src:predicate.toString()},{timeout}); return readSave(page); }
async function record(name,fn,page){ const start=Date.now(); try{const detail=await fn();results.push({name,status:'PASS',durationMs:Date.now()-start,detail});return detail;}catch(error){let screenshot=null;try{if(page){screenshot=path.join(OUTPUT,`${name}-failure.png`);await page.screenshot({path:screenshot,fullPage:true});}}catch{}results.push({name,status:'FAIL',durationMs:Date.now()-start,error:error.message,details:error.details||null,screenshot});throw error;} }
async function currentQuestion(page){ const prompt=(await page.locator('.questionText').textContent())?.trim(); const q=questionByPrompt.get(prompt); assert(q,'Quest prompt not found in source bank',{prompt}); return q; }
async function clickAnswer(page,choice,{rapid=false}={}){ const button=page.getByRole('button',{name:choice,exact:true}).first(); if(rapid)await button.evaluate(el=>{el.click();el.click();});else await button.click(); await page.locator('.feedback').waitFor({state:'visible'}); }
async function advance(page,counter){ await page.waitForFunction(previous=>document.querySelector('.qCounter')?.textContent?.trim()!==previous,counter,{timeout:2500}); }
async function solveCorrect(page,{rapid=false}={}){ const q=await currentQuestion(page); const counter=(await page.locator('.qCounter').textContent())?.trim(); const before=await readSave(page); const old=before.stats?.[q.skill]||{seen:0,correct:0,independentCorrect:0}; await clickAnswer(page,q.answer,{rapid}); const after=await waitSave(page,(value,args)=>{const [skill,seen,correct]=args;const s=value.stats?.[skill];return s?.seen>=seen&&s?.correct>=correct;},[q.skill,(old.seen||0)+1,(old.correct||0)+1],1500); if(rapid){const next=after.stats[q.skill];assert(next.seen===(old.seen||0)+1,'Rapid click duplicated seen evidence',{old,next});assert(next.correct===(old.correct||0)+1,'Rapid click duplicated correct evidence',{old,next});assert(next.independentCorrect===(old.independentCorrect||0)+1,'Rapid click duplicated independent evidence',{old,next});} await advance(page,counter); return {id:q.id,skill:q.skill,before:critical(before),after:critical(after)}; }
async function wrongRetryThenAssisted(page){ const q=await currentQuestion(page); const counter=(await page.locator('.qCounter').textContent())?.trim(); const wrong=q.choices.find(c=>c!==q.answer); const before=await readSave(page); const oldWrong=before.stats?.[q.skill]?.wrong||0; await clickAnswer(page,wrong); const first=await waitSave(page,(value,args)=>(value.stats?.[args[0]]?.wrong||0)>=args[1],[q.skill,oldWrong+1],1500); await page.getByRole('button',{name:/Try again with the clue/i}).click(); await clickAnswer(page,wrong); await page.waitForTimeout(100); const repeated=await readSave(page); assert(repeated.coins===first.coins&&repeated.xp===first.xp,'Repeated wrong retry farmed rewards'); assert(repeated.stats?.[q.skill]?.wrong===first.stats?.[q.skill]?.wrong,'Repeated wrong retry duplicated wrong evidence'); await page.getByRole('button',{name:/Try again with the clue/i}).click(); await clickAnswer(page,q.answer); const assisted=await waitSave(page,(value,args)=>(value.stats?.[args[0]]?.correct||0)>=args[1],[q.skill,(repeated.stats?.[q.skill]?.correct||0)+1],1500); assert(assisted.coins===repeated.coins,'Assisted success awarded Coins'); assert(assisted.stars===repeated.stars,'Assisted success awarded Mastery Star'); assert(assisted.transferWins===repeated.transferWins,'Assisted success awarded transfer evidence'); assert(JSON.stringify(assisted.mastered)===JSON.stringify(repeated.mastered),'Assisted success changed mastery'); await advance(page,counter); return {id:q.id,before:critical(before),firstWrong:critical(first),repeatedWrong:critical(repeated),assisted:critical(assisted)}; }

const today=new Date().toISOString().slice(0,10);
const seed={stateVersion:2,coins:1890,stars:50,xp:123,starWorth:887,owned:['tops-1','tops-2','tops-3','bottoms-1','shoes-1','beds-1','desks-1','companions-1','companions-3','future-no-art-999','future-no-art-room'],purchaseReceipts:['tops-2','tops-3'],equipped:{top:'tops-2',bottom:'bottoms-1',shoes:'shoes-1',companion:'companions-3',back:'future-no-art-999'},stats:{},mastered:['synthetic-skill'],roomDecor:['beds-1','future-no-art-room'],questsCompleted:7,transferWins:4,lastDailyKey:today,daily:{quests:0,transfers:0,purchase:2},dreamGoalId:'future-no-art-goal',districtProgress:{'Lantern Lane':2,'Story Street':3,'Wordwood Garden':4},companionBond:5,activeQuestReceipt:'',lastCompletedQuestReceipt:''};

const browser=await chromium.launch({headless:true});
const browserVersion=browser.version();
const context=await browser.newContext({viewport:{width:1408,height:1056}});
const page=await context.newPage();
let fatal=null;
try{
  await page.goto(BASE_URL,{waitUntil:'networkidle'});
  await page.evaluate(({key,seed})=>localStorage.setItem(key,JSON.stringify(seed)),{key:SAVE_KEY,seed});
  await page.reload({waitUntil:'networkidle'});

  await record('indexeddb-current-backup-before-recovery',async()=>{ const current=await readSave(page); assert(current.coins===seed.coins&&current.owned.includes('future-no-art-999'),'Seed did not load before recovery test',{current:critical(current)}); const backup=await waitIdb(page,v=>v.coins===seed.coins&&v.owned?.includes('future-no-art-999')); return {current:critical(current),backup:critical(backup)}; },page);

  await record('localstorage-loss-recovers-exact-indexeddb-state',async()=>{ const before=await readSave(page); await page.evaluate(key=>localStorage.removeItem(key),SAVE_KEY); await page.reload({waitUntil:'networkidle'}); const recovered=await waitSave(page,v=>v.coins===1890&&v.owned?.includes('future-no-art-999')&&v.equipped?.back==='future-no-art-999',[],5000); assert(JSON.stringify(critical(recovered))===JSON.stringify(critical(before)),'IndexedDB recovery did not restore exact critical state',{before:critical(before),recovered:critical(recovered)}); return {before:critical(before),recovered:critical(recovered)}; },page);

  await record('quest-retry-rapid-answer-and-final-refresh-before-ui-transition',async()=>{ await page.locator('.navBtn').filter({hasText:/Quest/i}).first().click(); const begin=page.getByRole('button',{name:/Begin Quest|Start 5-Action Quest/i}).first(); if(await begin.count())await begin.click(); await page.locator('.qCounter').waitFor({state:'visible'}); const beforeQuest=await readSave(page); const retry=await wrongRetryThenAssisted(page); const rapid=await solveCorrect(page,{rapid:true}); await solveCorrect(page); await solveCorrect(page); const final=await currentQuestion(page); const beforeFinal=await readSave(page); const start=Date.now(); await clickAnswer(page,final.answer); const committed=await waitSave(page,v=>Boolean(v.lastCompletedQuestReceipt)&&v.questsCompleted>=8,[],850); const commitMs=Date.now()-start; assert(commitMs<900,'Final Quest state not durable before 950ms presentation timer',{commitMs}); assert(committed.questsCompleted===beforeFinal.questsCompleted+1,'Quest completion duplicated/missed'); assert(committed.companionBond===beforeFinal.companionBond+1,'Bond completion duplicated/missed'); assert(committed.daily.quests===beforeFinal.daily.quests+1,'Daily Quest completion duplicated/missed'); assert(committed.coins>=beforeFinal.coins+30&&committed.xp>=beforeFinal.xp+30,'Final completion rewards missing'); await page.reload({waitUntil:'networkidle'}); const reloaded=await readSave(page); assert(reloaded.questsCompleted===committed.questsCompleted&&reloaded.companionBond===committed.companionBond&&reloaded.daily.quests===committed.daily.quests,'Immediate refresh changed completion side effects'); assert(reloaded.lastCompletedQuestReceipt===committed.lastCompletedQuestReceipt,'Completion receipt lost on refresh'); return {beforeQuest:critical(beforeQuest),retry,rapid,beforeFinal:critical(beforeFinal),commitMs,committed:critical(committed),reloaded:critical(reloaded)}; },page);

  await record('final-recovery-progress-invariants',async()=>{ const s=await readSave(page); assert(s.owned.includes('future-no-art-999')&&s.equipped.back==='future-no-art-999','Unknown/no-art inventory/equip lost'); assert(s.roomDecor.includes('future-no-art-room')&&s.dreamGoalId==='future-no-art-goal','Unknown/no-art room/Dream Goal lost'); assert(s.coins>=0&&s.stars>=0&&s.xp>=0,'Negative economy value'); assert(s.mastered.includes('synthetic-skill'),'Mastery evidence lost'); assert(s.districtProgress['Story Street']===3,'District progress changed'); return {state:critical(s)}; },page);
}catch(error){fatal=error;}
finally{ const report={status:fatal||results.some(r=>r.status==='FAIL')?'FAIL':'PASS',sourceHead:process.env.GITHUB_SHA||null,syntheticOnly:true,noRealPlayerData:true,browser:`Chromium ${browserVersion} via Playwright`,cases:results}; await fs.writeFile(path.join(OUTPUT,'report.json'),JSON.stringify(report,null,2)); await fs.writeFile(path.join(OUTPUT,'summary.txt'),[`PERSISTENCE_RECOVERY_QUEST_QA_STATUS=${report.status}`,`SOURCE_HEAD=${report.sourceHead||'unknown'}`,`BROWSER=${report.browser}`,`PASS=${results.filter(r=>r.status==='PASS').length}`,`FAIL=${results.filter(r=>r.status==='FAIL').length}`,...results.map(r=>`${r.status} ${r.name}${r.error?` :: ${r.error}`:''}`)].join('\n')+'\n'); await browser.close(); }
if(fatal||results.some(r=>r.status==='FAIL'))process.exit(1);
